version: '3.1'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - './data/redis:/data'
  
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
      
